/**
 * This is automatically generated by sprout plug-in.
 */
package com.furiganahub.api.common.service;

import java.util.HashMap;
import java.util.List;
import java.util.Map;

import javax.servlet.http.HttpServletRequest;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

import com.furiganahub.api.common.dao.SPCallerDAO;

/**
 * 
 * @since TODO
 * @author Administrator
 */
@Service
public class SPCallerService {

	@Autowired
	SPCallerDAO sPCallerDAO;

	/**
	 * Stored Procedure Parameter Matadata 조회
	 * 
	 * @param map에 key : I_SP_FULL_NAME value : Stored Procedure Name (Package로
	 *             Calling시 PackageName.StoredProcedrueName)
	 * @return
	 */
	public Map<String, Object> selectSPMetaData(Map<String, Object> map) {
		//
		HashMap<String, Object> hashMapMeta = (HashMap<String, Object>) sPCallerDAO.selectSPMetaData(map);
		return hashMapMeta;
	}

	/**
	 * Simple Stored Procedure 조회
	 * 
	 * @param map     I_SP_FULL_NAME value : Stored Procedure Name (Package로
	 *                Calling시 PackageName.StoredProcedrueName) I_SP_PARAM value :
	 *                List가 존재하여야 함 한건이라도 ArrayList 형식으로 보내야함 (JSON에서 보낼시 [
	 *                rowObject ];
	 * @param request
	 * @return
	 * @throws Exception
	 */
	public Map<String, Object> callSimpleSP(Map<String, Object> map, HttpServletRequest request) throws Exception {
		// TODO Auto-generated method stub
		String I_SP_FULL_NAME = (String) map.get("I_SP_FULL_NAME");
		String ARGUMENT_NAME = "";
		String DATA_TYPE = "";
		String IN_OUT = "";
		HashMap<String, Object> hashMapParam = (HashMap<String, Object>) map.get("I_SP_PARAM");

		// HashMap<String, Object> hashMapMeta = (HashMap<String, Object>)
		// sPCallerDAO.selectSPMetaData(map);
		List<Map<String, Object>> metaArgList = sPCallerDAO.selectSPMetaData(map);

		Map<String, Object> hashMapResult = sPCallerDAO.callSimpleSP(request, I_SP_FULL_NAME, metaArgList, hashMapParam,
				null);

		return hashMapResult;
		// return hashMapResult;
	}

	public Map<String, Object> callBatchSP(Map<String, Object> map, HttpServletRequest request) throws Exception {
		// TODO Auto-generated method stub
		return sPCallerDAO.callBatchSP(map, request);
	}

}
