package com.furiganahub.api.common.controller;
/**
 * This is automatically generated by sprout plug-in.
 */

import java.util.HashMap;
import java.util.Map;
import java.util.UUID;

import javax.servlet.http.HttpServletRequest;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.ui.Model;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;

import com.furiganahub.api.common.service.SPCallerService;

/**
 * 
 * @since
 * @author Administrator
 */
@RestController
@RequestMapping("/sPCaller")
public class SPCallerController {

	@Autowired
	SPCallerService sPCallerService;

	// @Autowired
	// private SessionUtil sessionUtil;

	@RequestMapping("/selectSPMetaData")
	public Map<String, Object> selectSPMetaData(@RequestBody Map<String, Object> map, Model model,
			HttpServletRequest request) {
		// sessionUtil.addUserBaseInfo(request.getSession(), (HashMap<String, Object>)
		// map);

		return sPCallerService.selectSPMetaData(map);
	}

	@RequestMapping("/callSimpleSP")
	public Map<String, Object> callSimpleSP(@RequestBody Map<String, Object> map, Model model,
			HttpServletRequest request) {

		Map<String, Object> result = new HashMap<String, Object>();
		try {
			return sPCallerService.callSimpleSP(map, request);
		} catch (Exception e) {
			result.put("O_SERVER_ERROR", e.getMessage());
			return result;
		}

	}

	@RequestMapping("/callBatchSP")
	public Map<String, Object> callBatchSP(@RequestBody Map<String, Object> map, Model model,
			HttpServletRequest request) {
		Map<String, Object> result = new HashMap<String, Object>();
		try {
			result = sPCallerService.callBatchSP(map, request);

		} catch (Exception e) {
			result.put("O_SERVER_ERROR", e.getMessage());

		}
		return null;
	}

	@RequestMapping("/getGUID")
	public Map<String, Object> getGUID(@RequestBody Map<String, Object> map, Model model, HttpServletRequest request) {
		map.put("O_GUID", UUID.randomUUID().toString());
		return map;
	}

}